---

- hosts: hostslist
  gather_facts: True
  remote_user: user
  tasks:
    - name: Check Operating System
      fail:
        msg="You're not running a supported operation system (CentOS or RHEL 7+)"
      when:
        - ansible_os_family != "Redhat"
        - ansible_distribution_major_version|int < 7
    - name: Print Operating System
      debug:
        msg="You're running {{ansible_os_family}} {{ansible_distribution_major_version}} or equivalent"
