#Add a line into yum.conf file
---

- hosts: localhost
  gather_facts: False
  remote_user: user
#  vars:
#    filename: "{{ file }}"
  tasks:
    - name:   
      lineinfile: dest=/etc/yum.conf line="exclude=irqbalance*,man-pages" state=present backup=True
#    - name:
#      lineinfile: dest="{{ filename }}" line="exclude=irqbalance*,man-pages" state="{{ state }}" backup=True
