#!/bin/bash

os_ver=`cat /etc/redhat-release|cut -d " " -f7|cut -d "." -f1`
file_move() { mv /etc/sysconfig/systemid /var/tmp
}
final_status() { if [[ $? eq 0 ]];then
echo "Successfully registered"
else
    echo "Unable to register"
    fi
}
execution_msg() { echo "running bootstrap script to register to sattlite"
}
reg_5_6() { wget -o --no-check-certificate https://sattlite.example.com/pub/bootstrap_script
}
reg_7() { wget -o --q --no-check-certificate https://sattlite.example.com/pub/bootstrap_script7


case $os_ver in

5|6)

file_move()

execution_msg()

reg_5_6()

final_status()

 ;;
 
 7)
 
 file_move()
 
 execution_msg()
 
 reg_7()
 
 final_status()
 ;;
 *)
 echo "Nothing to do"
 esac
 #created by zeeshan
 
 

