---
- hosts: localhost
  gather_facts: true
  vars_files:
    - all.yml
  remote_user: user
  tasks:
#    - name: Gathering user info
#      local_action: command whoami
#      register: youruser
#
    - name: Setup a system user
      user: name=exampleuser
            shell=/bin/bash
            generate_ssh_key=yes
            ssh_key_bits=2048
            ssh_key_file=./ssh/id_rsa
    - name: Add ssh public key to authorize_keys
      authorized_key:
        user=exampleuser
        key="{{ lookup('file','/home/user/.ssh/id_rsa.pub')}}"
        manage_dir=yes
      ignore_errors: true

    - name: Add other SSH public keys
      authorized_key:
        user=exampleuser
        key="{{ lookup('file','authorized_keys')}}"
