---
## optional Firewall role
## begin firewall
## we need TCP/80 and TCP/443 open
## detemine firewall status and take action
## 1) use firewall-cmd if firewalld is utilized
## 2) insert iptables rule if iptables is used
#
- hosts: hostslist
  gather_facts: True
  vars_files:
    - all.yml
  remote_user: user
  tasks:
#    # Firewalld
    - name: Determine if firewalld is in use
      shell: systemctl is-enabled firewalld.service|egrep -qv 'masked|disabled'
      ignore_errors: true
      register: firewalld_in_use
      no_log: 
      become: true

    - name: Determine if firewalld is active
      shell: systemctl is-active firewalld.service| grep -vq inactive
      ignore_errors: true
      register: firewalld_is_active
      no_log: true
      become: true

    - name: Determine if TPC/{{httpd_port}} is already active
      shell: firewall-cmd --list-ports | egrep -q "^{{httpd_port}}/tcp"
      ignore_errors: true
      register: firewalld_httpd_port_exists
      no_log: true
      become: true

    # add firewall rule via firewall-cmd
    - name: Add firewall rule for TCP/{{httpd_port}} (firewalld)
      command: "{{ item }}"
      with_items:
        - firewall-cmd --zone=public --add-port={{httpd_port}}/tcp --permanent
        - firewall-cmd --reload
      ignore_errors: true
      become: true
      when: firewalld_in_use.rc == 0 and firewalld_is_active.rc == 0 and firewalld_httpd_port_exists.rc != 0

    # iptables-service
    - name: Check firewall rules for TCP/{{httpd_port}} (iptables-services)
      shell: grep "dport {{httpd_port}} \-j ACCEPT" /etc/sysconfig/iptables |wc -l
      ignore_errors: true
      register: iptables_httpd_port_exists
      failed_when: iptables_httpd_ports_exists == 127
      no_log: true
      become: true

    - name: Add firewall rule for TCP/{{httpd_port}} (iptables-services)
      lineinfile:
        dest: /etc/sysconfig/iptables
        line: '-A INPUT -p tcp -m tcp --dport "{{httpd_port}}" -j ACCEPT'
        regexp: '^INPUT -i lo -j ACCEPT'
        insertbefore: '-A INPUT -i lo -j ACCEPT'
        backup: yes
      ignore_errors: true
      no_log: true
      when: firewalld_in_use.rc != 0 and firewalld_is_active.rc != 0 and iptables_httpd_port_exists.stdout| == 0
      become: true
      notify: restart iptables
          
  handlers:
    - name: retsart iptables
      become: true
      service:
        name: iptables
        state: restarted

